before_script:
  - pip install coverage
  - conda install -c bioconda -y minimap2
  - conda install pandas
  - cd test
functional tests:
  image: continuumio/miniconda3
  script:
    - coverage run -p ../miccr.py -d ./Refseq_viruses.fa     -i Refseq_viruses.fa   -p TEST_1 -v
    - coverage run -p ../miccr.py -d ./Refseq_viruses.fa.mmi -i Refseq_viruses.fa   -p TEST_2 -v
    - coverage run -p ../miccr.py -d ./Refseq_viruses.fa     -i Refseq_viruses.fa   -p TEST_3 -v  -x asm5    
    - coverage run -p ../miccr.py -d ./Refseq_viruses.fa     -i ERR2538127.fastq.gz -c            -x map-ont 
    - coverage run -p ../miccr.py -d ./Refseq_viruses.fa     -i ERR2538127.fastq.gz -p TEST_5 -v  -x map-ont 
    - coverage run -p ../miccr.py -d ./Refseq_viruses.fa     -i ERR2538127.fastq.gz -p TEST_6 -v  -x map-ont -t4
    - coverage run -p ../miccr.py -d ./Refseq_viruses.fa     -i ERR2538127.fastq.gz -p TEST_7 -v  -x map-ont -mp 0.05
    - coverage run -p ../miccr.py -d ./Refseq_viruses.fa     -i ERR2538127.fastq.gz -p TEST_8 -v  -x map-ont -if 0.5
    - cat TEST_8.ctg.tsv
    - cat TEST_8.lca_ctg.tsv
# coverage report
    - coverage combine
    - coverage report -m